### PR TITLE
added new ruleset for ublock orgin lite 

### PR DESCRIPTION
**Pull request by subham8907**
added new ruleset for ublock orgin lite independly  devloped by linkumori url purifer extension devloper i want to contribute my ruleset to ublock orgin lite project

### CODE REVIEW

**Comment by subham8907** [comment]
repo for my project is this https://github.com/subham8907/Linkumori

**Comment by subham8907** [comment]
This ruleset remove tracking parameter from urls

**Comment by stephenhawk8054** [comment]
Rulesets for uBOL are converted from [uAssets' filters](https://github.com/uBlockOrigin/uAssets), not from this repo. Please make issues / PRs there.

Also uBO could already cover the tracking parameters in the privacy list or in `AdGuard URL Tracking Protection` list already, so please report these issues to https://github.com/AdguardTeam/AdguardFilters/issues first.

**Comment by subham8907** [comment]
first of all this ruleset diffrent from adguard url tracking protection i donot redevloped the wheel first test it compare it

**Comment by subham8907** [comment]
check yourself

**Comment by stephenhawk8054** [comment]
If that list has not covered your parameters yet, please report to them, uBOL includes that list in the settings for users to enable.

Also as I said: 

> Rulesets for uBOL are converted from [uAssets' filters](https://github.com/uBlockOrigin/uAssets), not from this repo. Please make issues / PRs there.

**Comment by subham8907** [comment]
> If that list has not covered your parameters yet, please report to them, uBOL includes that list in the settings for users to enable.
> 
> Also as I said:
> 
> > Rulesets for uBOL are converted from [uAssets' filters](https://github.com/uBlockOrigin/uAssets), not from this repo. Please make issues / PRs there.

i said this ruleset are not converted from filter list

**Comment by stephenhawk8054** [comment]
Then it's not suitable for uBOL.

**Comment by subham8907** [comment]
why i should report to adguard 
doesnot make sense to me

**Comment by stephenhawk8054** [comment]
Parameters removal are converted from the filters like these:

https://github.com/uBlockOrigin/uAssets/blob/1be682a01d4157b2428e4f1a4f32a4c05001d173/filters/privacy.txt#L923-L925

We don't make rulesets independently. All rulesets in uBOL are made from uBO's filter syntaxes first.

**Comment by subham8907** [comment]
so you are saying i have to made convert all dnr rules to ublock filter list then you convert to dnr ruleset

**Comment by stephenhawk8054** [comment]
Yes, the rulesets are converted automatically using [uBlock repo tools](https://github.com/gorhill/uBlock/tree/master/tools) after fetching the filters in [uAssets repo](https://github.com/uBlockOrigin/uAssets). We don't add any DNR rulesets manually.

**Pull request closed without merging**
