### PR TITLE
patches for issue #199  

### PR DESCRIPTION
**Pull request by subham8907**
Added new patches for "internal error" issue #199 
https://github.com/uBlockOrigin/uBOL-home/issues/199

### CODE REVIEW

**Comment by subham8907** [comment]
we donot know if issue #199 occured in firefox if issue occuered we can implement simillar patch on firefox

**Comment by gorhill** [comment]
I consider the issue already fixed, so I will decline the pull request.

**Comment by subham8907** [comment]
can you provide step to reproduce this issue it seems issue occured inconsitently if you provide it would be helpfull

**Comment by gorhill** [comment]
An _internal error_ was reported, and this happened at random after an extension updated to a new version. I ended up seeing the error on my side after I build a new version of uBOL and launched the browser with the new version being loaded. As long as I did not force a reload of the extension, the error kept happening at each browser launch.

**Pull request closed without merging**
