### PR TITLE
Keep rulesets that are enabled in manifest.json during installation

### LINKED ISSUE #143: Pre-enabled rulesets in manifest.json are being disabled by `defaultRulesetsFromLanguage`
During the installation of the extension, the `defaultRulesetsFromLanguage` function uses a hard-coded `out` containing the default ruleset only (on ruleset-manager.js:437) so any enabled ruleset from the manifest.json that is not "default" and the language default is being disabled during installation

To fix this, that line should be 
```
const out = await dnr.getEnabledRulesets();
```

I will open a PR on this repo hoping that's the way to contribute to this version of uBO 🙏

### PR DESCRIPTION
**Pull request by m3nadav**
Resolves #143

### CODE REVIEW

**Review by subham8907 — APPROVED** [review]

**Comment by m3nadav** [comment]
Why was this closed?
I understand this repo is a generated build of the script in https://github.com/gorhill/uBlock/tree/master/platform/mv3 I just don't have permission to open PRs in the `gorhill/uBlock` repo

**Comment by gorhill** [comment]
You can create a patch in your own forked repo of `https://github.com/gorhill/uBlock/`, and then point me to the patch and I will pull it from your repo. Once your patch is pulled, you will become a collaborator and will be able to submit pull requests directly to `https://github.com/gorhill/uBlock/` in the future without the hurdle, which is in place to avoid spurious interactions with the repo to avoid burden.

**Comment by m3nadav** [comment]
My forked [PR](https://github.com/scrollai/uBlock/pull/1)

**Comment by gorhill** [comment]
<https://github.com/gorhill/uBlock/commit/2782b16ecf4e25414ca1b27a144535676a764740> merged.

**Pull request closed without merging**
